/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const KpiConfig = IDL.Record({
  'title' : IDL.Text,
  'trend' : IDL.Text,
  'value' : IDL.Text,
  'change' : IDL.Text,
});
export const ChartConfig = IDL.Record({
  'title' : IDL.Text,
  'chartType' : IDL.Text,
  'data' : IDL.Text,
  'xKey' : IDL.Text,
  'yKeys' : IDL.Vec(IDL.Text),
});
export const DashboardConfig = IDL.Record({
  'aiInsights' : IDL.Vec(IDL.Text),
  'generatedAt' : IDL.Int,
  'kpis' : IDL.Vec(KpiConfig),
  'chartConfigs' : IDL.Vec(ChartConfig),
  'fileId' : IDL.Text,
});
export const FileMetadata = IDL.Record({
  'columnNames' : IDL.Vec(IDL.Text),
  'fileName' : IDL.Text,
  'fileType' : IDL.Text,
  'dataPreview' : IDL.Text,
  'fileId' : IDL.Text,
  'rowCount' : IDL.Nat,
  'uploadedAt' : IDL.Int,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'getApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getDashboardConfig' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DashboardConfig)],
      ['query'],
    ),
  'getFileMetadata' : IDL.Func([IDL.Text], [IDL.Opt(FileMetadata)], ['query']),
  'getLatestDashboard' : IDL.Func([], [IDL.Opt(DashboardConfig)], ['query']),
  'getLatestFileId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUserFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getVoiceLanguage' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'saveApiKey' : IDL.Func([IDL.Text], [], []),
  'saveDashboardConfig' : IDL.Func([DashboardConfig], [], []),
  'saveFileMetadata' : IDL.Func([FileMetadata], [], []),
  'saveVoiceLanguage' : IDL.Func([IDL.Text], [], []),
  'sendChatMessage' : IDL.Func(
      [IDL.Vec(ChatMessage), IDL.Text],
      [IDL.Text],
      [],
    ),
  'setLatestFileId' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const KpiConfig = IDL.Record({
    'title' : IDL.Text,
    'trend' : IDL.Text,
    'value' : IDL.Text,
    'change' : IDL.Text,
  });
  const ChartConfig = IDL.Record({
    'title' : IDL.Text,
    'chartType' : IDL.Text,
    'data' : IDL.Text,
    'xKey' : IDL.Text,
    'yKeys' : IDL.Vec(IDL.Text),
  });
  const DashboardConfig = IDL.Record({
    'aiInsights' : IDL.Vec(IDL.Text),
    'generatedAt' : IDL.Int,
    'kpis' : IDL.Vec(KpiConfig),
    'chartConfigs' : IDL.Vec(ChartConfig),
    'fileId' : IDL.Text,
  });
  const FileMetadata = IDL.Record({
    'columnNames' : IDL.Vec(IDL.Text),
    'fileName' : IDL.Text,
    'fileType' : IDL.Text,
    'dataPreview' : IDL.Text,
    'fileId' : IDL.Text,
    'rowCount' : IDL.Nat,
    'uploadedAt' : IDL.Int,
  });
  const ChatMessage = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'getApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getDashboardConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DashboardConfig)],
        ['query'],
      ),
    'getFileMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FileMetadata)],
        ['query'],
      ),
    'getLatestDashboard' : IDL.Func([], [IDL.Opt(DashboardConfig)], ['query']),
    'getLatestFileId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUserFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getVoiceLanguage' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'saveApiKey' : IDL.Func([IDL.Text], [], []),
    'saveDashboardConfig' : IDL.Func([DashboardConfig], [], []),
    'saveFileMetadata' : IDL.Func([FileMetadata], [], []),
    'saveVoiceLanguage' : IDL.Func([IDL.Text], [], []),
    'sendChatMessage' : IDL.Func(
        [IDL.Vec(ChatMessage), IDL.Text],
        [IDL.Text],
        [],
      ),
    'setLatestFileId' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };