/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface FileMetadata {
    columnNames: Array<string>;
    fileName: string;
    fileType: string;
    dataPreview: string;
    fileId: string;
    rowCount: bigint;
    uploadedAt: bigint;
}
export interface DashboardConfig {
    aiInsights: Array<string>;
    generatedAt: bigint;
    kpis: Array<KpiConfig>;
    chartConfigs: Array<ChartConfig>;
    fileId: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface KpiConfig {
    title: string;
    trend: string;
    value: string;
    change: string;
}
export interface ChatMessage {
    content: string;
    role: string;
}
export interface ChartConfig {
    title: string;
    chartType: string;
    data: string;
    xKey: string;
    yKeys: Array<string>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface backendInterface {
    getApiKey(): Promise<string | null>;
    getDashboardConfig(fileId: string): Promise<DashboardConfig | null>;
    getFileMetadata(fileId: string): Promise<FileMetadata | null>;
    getLatestDashboard(): Promise<DashboardConfig | null>;
    getLatestFileId(): Promise<string | null>;
    getUserFiles(): Promise<Array<FileMetadata>>;
    getVoiceLanguage(): Promise<string | null>;
    saveApiKey(apiKey: string): Promise<void>;
    saveDashboardConfig(config: DashboardConfig): Promise<void>;
    saveFileMetadata(metadata: FileMetadata): Promise<void>;
    saveVoiceLanguage(lang: string): Promise<void>;
    sendChatMessage(messages: Array<ChatMessage>, apiKey: string): Promise<string>;
    setLatestFileId(fileId: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { DashboardConfig as _DashboardConfig, FileMetadata as _FileMetadata } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getApiKey(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiKey();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiKey();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardConfig(arg0: string): Promise<DashboardConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardConfig(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardConfig(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFileMetadata(arg0: string): Promise<FileMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileMetadata(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileMetadata(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestDashboard(): Promise<DashboardConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestDashboard();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestDashboard();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestFileId(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestFileId();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestFileId();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserFiles(): Promise<Array<FileMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserFiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserFiles();
            return result;
        }
    }
    async getVoiceLanguage(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoiceLanguage();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoiceLanguage();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveApiKey(arg0);
            return result;
        }
    }
    async saveDashboardConfig(arg0: DashboardConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDashboardConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDashboardConfig(arg0);
            return result;
        }
    }
    async saveFileMetadata(arg0: FileMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFileMetadata(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFileMetadata(arg0);
            return result;
        }
    }
    async saveVoiceLanguage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVoiceLanguage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVoiceLanguage(arg0);
            return result;
        }
    }
    async sendChatMessage(arg0: Array<ChatMessage>, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0, arg1);
            return result;
        }
    }
    async setLatestFileId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLatestFileId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLatestFileId(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DashboardConfig]): DashboardConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileMetadata]): FileMetadata | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
